---
  
- name: Latest stable version of Nginx
  apt_repository: repo='ppa:nginx/stable'

- name: Install nginx
  apt: name=nginx state=present update_cache=yes

- name: Copy nginx configuration for phpldapadmin
  template: src={{ item }} dest=/etc/nginx/sites-available/ mode=0755
  with_items:
  - phpldapadmin

- name: Create symlink
  file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
  with_items:
  - phpldapadmin

- name: disable default nginx conf
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
